### PR TITLE
Feature apple clone

### PR DESCRIPTION
**Pull request by jstloyal**
#### What does this PR do?

- Shows how to build with backgrounds and gradients

### Description of Task to be completed?

 - Added the HTML index file
 - Added CSS to style, add background and gradients. 
 - Ran validations on my HTML
Apple Home Page Clone
 and CSS. 

#### How should this be manually tested? 

- Clone this branch. 
- open the index.html
- file on your browser 

#### Screenshot 
Screenshot_2020-03-08 Apple Home Page Clone

### CODE REVIEW

**Comment by lekegitrepo** [comment]
### Hi @jstloyal 👏 👏
#### You have done a good job on this project but you still need to make some required changes. Check my comments below.

**_1. The bottom section's four elements that contain images should be links_** (to other articles or #) ([link to page](https://web.archive.org/web/20140301004610/http://www.apple.com/))

**_2. Fix the screenshot link in the readme._**

**_3. Files not related to the project should not be committed and added to .gitignore (e.g. `.vscode` folder)_** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

**_4. Style rule in line 157 of the stylesheet is invalid._**
image

**_5. Try to make the page fit the browser window like the original._**

**_Your page has horizontal scroll bar:_**

scroll-bar

**_The original page:_**

image

**_Kindly make the above required changes and submit for review._**

**If you have any doubt or question contact me on slack.**

### Reviewed by: _Temitayo Adeleke_

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require changes.

**Comment by jstloyal** [comment]
My screen resolution is high, and the page fits my browser window like the original. But I have further reduced the width.

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🚥 ♻️ 

Hi @jstloyal, you have done a great job fixing some of the changes requested by the previous reviewer 😄 . I am sorry my colleague did not point one of the main requirements. 👍 Kindly fix the comments below:
- ```The bottom``` part on ```line 37 - 42```. Let us replace the `````` with a ```<div>``` and give it a class and set the background-image or background-url for each of the child of ```<aside>```. The main objective is using background and gradient
- A quick fix to the horizontal scroll as pointed out by the previous reviewer is to add ```width:100%``` to ```.bottom-aside```
- Let us add a link to the copyright text in the ```<footer>```

Kindly make these changes and submit another code review 🙂 
_Happy coding_ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo-9738b0128/)

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Comment by lekegitrepo** [comment]
## Hi @jstloyal 👏 💯 
### You have put a lot of effort into this project and you have implemented the required changes.
### This project is approved.

### Note: About the horizontal scroll bar it's still there on the normal browser window but when I inspect it using the developer tool the page is normal (without horizontal scroll bar).

image

### Reviewed by: Temitayo Adeleke

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — APPROVED** [review]
## Status: Approved

**Pull request merged**
